services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: pnpm run dev
